font:
  normal:
    family: VictorMono Nerd Font
    style: regular
  size: 11
colors:
  primary:
    background: '#000000'
  normal:
    black: '#000000'
  bright:
    black: '#404040'
window:
  opacity: 1
  padding:
    x: 10
    y: 10
cursor:
  style:
    shape: Underline
draw_bold_text_with_bright_colors: true
shell:
  program: /usr/bin/fish
